services:
  api:
    build:
      context: ./api-application
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map API port
    environment:
      DATABASE_URL: postgresql://postgres_adm:postgres@db:5432/recruitment
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres_adm
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recruitment
    ports:
      - "5433:5432"  # Map Postgres port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  admin:
    build:
      context: ./recruitment-admin-application
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map Admin frontend port
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
