name: Deploy Recruitment App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Project Structure
        run: ls -R

      - name: Build and Start Containers
        run: docker compose --env-file .env.prod -f docker-compose.prod.yml up -d --build

      - name: Show Running Containers
        run: docker ps