name: Deploy Recruitment App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Show Project Structure (debug)
        run: ls -R

      - name: 3. Build Docker Containers
        run: docker compose build

      - name: 4. Start Containers
        run: docker compose up -d

      - name: 5. Show Running Containers
        run: docker ps